# Importing Necessary Library

In [55]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report
from imblearn.under_sampling import RandomUnderSampler
from sklearn.linear_model import  LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC


# Reading The Data

In [56]:
data=pd.read_csv("creditcard.csv")

# Basic EDA

In [57]:
data.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [58]:
data.shape

(284807, 31)

In [59]:
#Prediction Column
data["Class"].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [60]:
# No Null Values
data.isna().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [61]:
#Duplicate Rows
data[data.duplicated()]

Time        V1        V2        V3        V4        V5        V6  \
33          26.0 -0.529912  0.873892  1.347247  0.145457  0.414209  0.100223   
35          26.0 -0.535388  0.865268  1.351076  0.147575  0.433680  0.086983   
113         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
114         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
115         74.0  1.038370  0.127486  0.184456  1.109950  0.441699  0.945283   
...          ...       ...       ...       ...       ...       ...       ...   
282987  171288.0  1.912550 -0.455240 -1.750654  0.454324  2.089130  4.160019   
283483  171627.0 -1.464380  1.368119  0.815992 -0.601282 -0.689115 -0.487154   
283485  171627.0 -1.457978  1.378203  0.811515 -0.603760 -0.711883 -0.471672   
284191  172233.0 -2.667936  3.160505 -3.355984  1.007845 -0.377397 -0.109730   
284193  172233.0 -2.691642  3.123168 -3.339407  1.017018 -0.293095 -0.167054   

              V7        V8        V9  ...       V21       V22       V23  \
33      0.711206  0.176066 -0.286717  ...  0.046949  0.208105 -0.185548   
35      0.693039  0.179742 -0.285642  ...  0.049526  0.206537 -0.187108   
113    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
114    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
115    -0.036715  0.350995  0.118950  ...  0.102520  0.605089  0.023092   
...          ...       ...       ...  ...       ...       ...       ...   
282987 -0.881302  1.081750  1.022928  ... -0.524067 -1.337510  0.473943   
283483 -0.303778  0.884953  0.054065  ...  0.287217  0.947825 -0.218773   
283485 -0.282535  0.880654  0.052808  ...  0.284205  0.949659 -0.216949   
284191 -0.667233  2.309700 -1.639306  ...  0.391483  0.266536 -0.079853   
284193 -0.745886  2.325616 -1.634651  ...  0.402639  0.259746 -0.086606   

             V24       V25       V26       V27       V28  Amount  Class  
33      0.001031  0.098816 -0.552904 -0.073288  0.023307    6.14      0  
35      0.000753  0.098117 -0.553471 -0.078306  0.025427    1.77      0  
113    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
114    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
115    -0.626463  0.479120 -0.166937  0.081247  0.001192    1.18      0  
...          ...       ...       ...       ...       ...     ...    ...  
282987  0.616683 -0.283548 -1.084843  0.073133 -0.036020   11.99      0  
283483  0.082926  0.044127  0.639270  0.213565  0.119251    6.82      0  
283485  0.083250  0.044944  0.639933  0.219432  0.116772   11.93      0  
284191 -0.096395  0.086719 -0.451128 -1.183743 -0.222200   55.66      0  
284193 -0.097597  0.083693 -0.453584 -1.205466 -0.213020   36.74      0  

[1081 rows x 31 columns]

# Model Training

## Creating Dependent and Independnt Variable

In [62]:
x=data.drop(columns="Class")
y=data["Class"]

## OverSampling And UnderSampling

In [63]:
from imblearn.over_sampling import RandomOverSampler

In [64]:
randomOverSampler=RandomOverSampler()

In [65]:
randomUnderSampler=RandomUnderSampler()

In [66]:
x_resampled, y_resampled = randomOverSampler.fit_resample(x, y)

In [67]:
x_resampled

Time         V1         V2         V3         V4         V5  \
0            0.0  -1.359807  -0.072781   2.536347   1.378155  -0.338321   
1            0.0   1.191857   0.266151   0.166480   0.448154   0.060018   
2            1.0  -1.358354  -1.340163   1.773209   0.379780  -0.503198   
3            1.0  -0.966272  -0.185226   1.792993  -0.863291  -0.010309   
4            2.0  -1.158233   0.877737   1.548718   0.403034  -0.407193   
...          ...        ...        ...        ...        ...        ...   
568625  118532.0  -5.961457   5.313382  -6.674320   6.028975  -1.387560   
568626  102542.0  -1.456876   3.740306  -7.404518   7.440964  -1.549878   
568627   41204.0  -8.440284   6.147653 -11.683706   6.702780  -8.155839   
568628   75851.0  -4.793667   3.418911  -5.074445   4.035987  -3.527875   
568629   95628.0 -17.518909  12.572118 -19.038538  11.190895 -13.554721   

              V6         V7        V8        V9  ...       V20       V21  \
0       0.462388   0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361  -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499   0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203   0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921   0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...        ...       ...       ...  ...       ...       ...   
568625  0.670638  -4.128987 -4.765894 -1.005259  ... -1.116581  5.556642   
568626 -1.661697  -5.757213  1.615011 -2.194881  ...  0.529557  0.957897   
568627 -3.716264 -12.407313  5.626571 -6.232161  ...  0.520732  2.192855   
568628 -1.923242  -5.065981  1.996885 -3.097379  ...  0.342122  1.168618   
568629 -0.411924 -23.189397 -5.301412 -8.630390  ...  2.528512 -4.969478   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
568625 -1.501808  1.355172  0.141093  0.077913  0.473988  0.287129  1.468653   
568626  0.145339 -0.044704 -0.544962 -0.757757 -0.005352  0.318152 -0.323554   
568627 -0.282597  0.008068  0.403858 -0.018788  0.522722  0.792691  0.067790   
568628  0.289531 -0.371888  0.144761  0.084735 -0.197431  0.328672  0.835395   
568629  0.976125  1.841248  0.334418 -0.720128 -0.232603 -3.021992 -0.478158   

        Amount  
0       149.62  
1         2.69  
2       378.66  
3       123.50  
4        69.99  
...        ...  
568625  105.89  
568626    2.28  
568627   30.26  
568628   99.85  
568629    1.63  

[568630 rows x 30 columns]

In [68]:

x_resampled, y_resampled = randomUnderSampler.fit_resample(x, y)


In [69]:
x_resampled

Time         V1         V2        V3        V4        V5  \
189309  128345.0 -14.026514 -15.733166 -1.163953  1.160607  3.700101   
248515  153978.0  -1.370805  -1.576157  0.107768 -2.533271 -2.002829   
242687  151601.0   2.040211  -0.146975 -2.955934 -0.578356  2.609358   
69965    53654.0  -2.929930  -4.546605  1.234867 -1.726152 -0.343619   
204392  135255.0  -0.253161   1.264191 -0.686842 -0.599983  0.667620   
...          ...        ...        ...       ...       ...       ...   
279863  169142.0  -1.927883   1.125653 -4.518331  1.749293 -1.566487   
280143  169347.0   1.378559   1.289381 -5.004247  1.411850  0.442581   
280149  169351.0  -0.676143   1.126366 -2.213700  0.468308 -1.120541   
281144  169966.0  -3.113832   0.585864 -5.399730  1.817092 -0.840618   
281674  170348.0   1.991976   0.158476 -2.583441  0.408670  1.151147   

              V6        V7        V8        V9  ...       V20       V21  \
189309 -4.919323 -3.994219  0.040597  0.526429  ... -1.689825 -1.036948   
248515 -0.191287  2.903758 -0.365854  1.433184  ...  1.302394  0.105438   
242687  3.142642 -0.416883  0.784393  0.359902  ... -0.120714 -0.352334   
69965  -0.616041  0.274602 -0.131172 -1.933450  ...  1.670452  0.409961   
204392 -0.543956  0.530741  0.456522 -0.552242  ... -0.060532 -0.228481   
...          ...       ...       ...       ...  ...       ...       ...   
279863 -2.010494 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584   
280143 -1.326536 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612   
280149 -0.003346 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826   
281144 -2.943548 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276   
281674 -0.096695  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350   

             V22       V23       V24       V25       V26       V27       V28  \
189309 -0.533396 -2.681694  0.283554  0.490448 -0.110631 -0.065502  4.064853   
248515 -0.623551  1.516783 -0.069403 -0.076088 -1.317608 -0.013312  0.218970   
242687 -0.996937  0.363485  0.604827 -0.264560  0.219671 -0.039209 -0.042787   
69965  -0.158863  1.456081 -0.747928  0.774820 -0.168540 -0.404022 -0.077321   
204392 -0.651084  0.155371  0.612437 -0.443001  0.093284  0.099394  0.012892   
...          ...       ...       ...       ...       ...       ...       ...   
279863 -0.319189  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968   
280143  0.028234 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637   
280149  0.834108  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   
281144 -0.269209 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700   
281674 -0.295135 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   

        Amount  
189309  351.23  
248515  659.56  
242687    1.98  
69965   632.00  
204392    3.91  
...        ...  
279863  390.00  
280143    0.76  
280149   77.89  
281144  245.00  
281674   42.53  

[984 rows x 30 columns]

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)


# Feature Selection

In [71]:
data

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [72]:
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import SelectKBest

In [73]:
X_new = SelectKBest(f_classif, k=5).fit_transform(x, y)

In [74]:
X_new[0]

array([ 0.09079417, -0.61780086, -0.31116935, -0.47040053,  0.20797124])

In [75]:

x_resampled, y_resampled = randomUnderSampler.fit_resample(X_new, y)
xtrain, xtest, ytrain, ytest = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train = scaler.fit_transform(x_train)
X_test = scaler.transform(x_test)


In [76]:
modelLinearRegression = LogisticRegression()
modelLinearRegression.fit(xtrain,ytrain)
ypredLogisticRegresion=modelLinearRegression.predict(xtest)


In [77]:
print("Logistic Regression Results:")
print("Confusion Matrix:")
print(confusion_matrix(ytest, ypredLogisticRegresion))
print("\nClassification Report:")
print(classification_report(ytest, ypredLogisticRegresion))

Logistic Regression Results:
Confusion Matrix:
[[96  3]
 [14 84]]

Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.97      0.92        99
           1       0.97      0.86      0.91        98

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



## User Input

In [78]:
result=modelLinearRegression.predict([[0.09079417, -0.61780086, -0.31116935, -0.47040053,  0.20797124]])
if result:
    print(f"The Credit Card is Not Fake")
else:
    print("The Credit Card is Fake")

The Credit Card is Fake


# SVC

In [79]:
model_svc = SVC()
model_svc.fit(xtrain, ytrain)
ypred_svc = model_svc.predict(xtest)

print("Support Vector Classifier Results:")
print("Confusion Matrix:")
print(confusion_matrix(ytest, ypred_svc))
print("\nClassification Report:")
print(classification_report(ytest, ypred_svc))

Support Vector Classifier Results:
Confusion Matrix:
[[99  0]
 [18 80]]

Classification Report:
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        99
           1       1.00      0.82      0.90        98

    accuracy                           0.91       197
   macro avg       0.92      0.91      0.91       197
weighted avg       0.92      0.91      0.91       197



## User Input

In [80]:
result=model_svc.predict([[0.09079417, -0.61780086, -0.31116935, -0.47040053,  0.20797124]])
if result:
    print(f"The Credit Card is Not Fake")
else:
    print("The Credit Card is Fake")

The Credit Card is Fake


# Decision Tree


In [81]:
model_decision_tree = DecisionTreeClassifier()
model_decision_tree.fit(xtrain, ytrain)
ypred_decision_tree = model_decision_tree.predict(xtest)

print("Decision Tree Classifier Results:")
print("Confusion Matrix:")
print(confusion_matrix(ytest, ypred_decision_tree))
print("\nClassification Report:")
print(classification_report(ytest, ypred_decision_tree))

Decision Tree Classifier Results:
Confusion Matrix:
[[91  8]
 [10 88]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.92      0.91        99
           1       0.92      0.90      0.91        98

    accuracy                           0.91       197
   macro avg       0.91      0.91      0.91       197
weighted avg       0.91      0.91      0.91       197



## USer Input

In [82]:
result=model_decision_tree.predict([[0.09079417, -0.61780086, -0.31116935, -0.47040053,  0.20797124]])
if result:
    print(f"The Credit Card is Not Fake")
else:
    print("The Credit Card is Fake")

The Credit Card is Fake


# Random Forest Regressor

In [83]:
model_random_forest = RandomForestClassifier(n_estimators=100, random_state=42)
model_random_forest.fit(xtrain, ytrain)
ypred_random_forest = model_random_forest.predict(xtest)

print("Random Forest Classifier Results:")
print("Confusion Matrix:")
print(confusion_matrix(ytest, ypred_random_forest))
print("\nClassification Report:")
print(classification_report(ytest, ypred_random_forest))

Random Forest Classifier Results:
Confusion Matrix:
[[94  5]
 [11 87]]

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.95      0.92        99
           1       0.95      0.89      0.92        98

    accuracy                           0.92       197
   macro avg       0.92      0.92      0.92       197
weighted avg       0.92      0.92      0.92       197



# User Input

In [84]:
result=model_random_forest.predict([[0.09079417, -0.61780086, -0.31116935, -0.47040053,  0.20797124]])
if result:
    print(f"The Credit Card is Not Fake")
else:
    print("The Credit Card is Fake")

The Credit Card is Fake
